### PR TITLE
Update Melissa's bio and photo

### PR DESCRIPTION
**Pull request by mngau**

### CODE REVIEW

**Comment by mngau** [comment]
Not really sure why @tpartington and @stan1y's changes are in this PR as well.
So hopefully I created this PR correctly.

**Comment by stan1y** [comment]
Did you rebase?

**Comment by mngau** [comment]
Yes I did, am I not meant to?

**Comment by stan1y** [comment]
rebase is correct but still strange result

**Comment by stevemac007** [comment]
Looks good

**Pull request merged**
