### PR TITLE
Master

### PR DESCRIPTION
**Pull request by folourdream**
Added profile for ranjeet pethe. Pls review.

### CODE REVIEW

**Comment by stan1y** [comment]
12 commits? seems like something is wrong here

**Comment by stevemac007** [comment]
There don't seem to be any files in this commit?

**Comment by stevemac007** [comment]
Plz create a PR into 'develop' with your changes so we can review on the beta site, and then we will merge and release off master.

**Comment by mngau** [comment]
Some minor gramma things to change please (e.g. adding spaces after punctuation and using Australian spelling):

> Ranjeet is a multifaceted software consultant. Over his two decades of consulting he has played multiple roles such as tester, iteration manager, test strategist, business analyst, team lead and hacky developer. Ranjeet is extremely passionate about optimisation and strongly believes in 'Jugaad' and 'YAGNI', he misses no opportunity to implement either of these approaches wherever possible.

**Pull request closed without merging**
