### PR TITLE
Adding bio

### PR DESCRIPTION
**Pull request by jags14385**
* Adding bio of James Strain
* Adding bio of Jagannath

### CODE REVIEW

**Comment by nonspecialist** [comment]
LGTM :shipit:

**Comment by mngau** [comment]
In James's bio please remove the comma after "delivery, "

**Comment by mngau** [comment]
In Jagan's bio might need to add a space after Automation... "Test Automation, Devops(Docker, AWS), "

**Comment by nonspecialist** [comment]
disagree about the comma in James' bio ... it's an Oxford Comma

**Pull request merged**
