### PR TITLE
use sans-serif font everywhere (better readability), avoid pixel base…

### PR DESCRIPTION
**Pull request by tpartington**
…d font sizing, don't load unused fonts

### CODE REVIEW

**Comment by mngau** [comment]
With the new font, it looks like some of the 'subheadings' are smaller.
From 
image

To
image

**Comment by mngau** [comment]
But it looks very similar in terms of readability to me 👍

**Comment by tpartington** [comment]
ah yep, i changed the way the font-sizing works as well, i'll tried to match the sizes but missed these subheadings, i'll try and get them closer.
good pickup.
Thanks.

**Comment by mngau** [comment]
The contact us is much more readable though 👍 
image

**Comment by mngau** [comment]
New one definitely appears more readable
From
image


To 
image

**Comment by mngau** [comment]
I'd suggest making the News subheadings here a little larger
image

**Pull request merged**
